### ISSUE TITLE
在地狱死亡后丢掉册子后拿到尸体。背包内的物品一直在窗口显示。

### ISSUE THREAD

**Issue by wrpota** [blackwhita/Expert-of-Magic-Art-World#8]
丢掉或者把物品放入箱子对于物品图标会消失。但是只要拿到死亡时的物品就会出现，因为这个原因坏档了。。最新版本

**Comment by wrpota** [comment]
![2023-04-26_20 03 21](https://user-images.githubusercontent.com/21377464/234569250-d42facaf-42d7-4008-8b99-bf260d55aade.png)
新开的档也有这个问题了。不能获取新物品，不然就会出现

**Comment by blackwhita** [comment]
https://www.mcmod.cn/class/3395.html，这个模组的问题，你需要关掉某些配置来解决
